"""
wpsstore Employee Data - Wholesale Price Shopping Branch
These employees belong to the wpsstore (branch) account only
"""

"""
wpsstore Employee Data - Wholesale Price Shopping Branch
These employees belong to the wpsstore (branch) account only
"""

wpsstore_users = {
    "Wholesalepriceshopping27@gmail.com": {
        "password": "WPS@123",
        "name": "WPS Branch Admin",
        "employee_number": "ADMIN001",
        "phone": "",
        "parent_phone": "",
        "job_role": "Office Admin",
        "total_leave": 0,
        "total_working": 0,
        "address": "",
        "aadhaar": "",
        "pan": "",
        "dob": "",
        "gender": "",
        "native": ""
    },
    "ayishabanu136@gmail.com": {
        "password": "Wps@12345",
        "name": "Ayisha banu",
        "employee_number": "WPS001",
        "phone": "6374929084",
        "parent_phone": "8344658058",
        "job_role": "Employee",
        "total_leave": 0,
        "total_working": 0,
        "address": "517/A2 Thirupathi Nagar, dasanoor, dhasampalyem govt. school back side, mettupalyem, 641301",
        "aadhar": "944505807040",
        "pan_card": "HSFPB4854H",
        "dob": "",
        "gender": "",
        "native": ""
    },
    "safrinabarvin12@gmail.com": {
        "password": "Wps@12345",
        "name": "S.Safrina Barvin",
        "employee_number": "WPS002",
        "phone": "9345972834",
        "parent_phone": "9345972834",
        "job_role": "Employee",
        "total_leave": 0,
        "total_working": 0,
        "address": "Kannagi street, sulesswaranpatti, pollachi",
        "aadhaar": "812344446351",
        "pan": "PYJPS2509J",
        "dob": "",
        "gender": "Female",
        "native": "Pollachi"
    },
    "keerthanasuresh1604@gmail.com": {
        "password": "Wps@12345",
        "name": "Keerthana Suresh",
        "employee_number": "WPS003",
        "phone": "7305629734",
        "parent_phone": "7305629734",
        "job_role": "Employee",
        "total_leave": 0,
        "total_working": 0,
        "address": "Omr thoraipakkam, Chennai",
        "aadhaar": "968023644564",
        "pan": "PRDPK5781F",
        "dob": "",
        "gender": "female",
        "native": "Villupuram, adukkam, mariyamman kovil street"
    },
    "reno770839@gmail.com": {
        "password": "Wps@12345",
        "name": "Renosha.J",
        "employee_number": "WPS004",
        "phone": "8148045758",
        "parent_phone": "7639108673",
        "job_role": "Employee",
        "total_leave": 0,
        "total_working": 0,
        "address": "Rangaipillai street anaimalai",
        "aadhaar": "421085247363",
        "pan": "EUPPR9090N",
        "dob": "",
        "gender": "female",
        "native": "Anaimalai"
    },
    "Rangeela@121gmail.com": {
        "password": "Wps@12345",
        "name": "K.Rangeela Devi",
        "employee_number": "WPS005",
        "phone": "9600995007",
        "parent_phone": "9578814056",
        "job_role": "Employee",
        "total_leave": 0,
        "total_working": 0,
        "address": "3/27/7, Rose garden, Suleeswaranpatti, Pollachi",
        "aadhaar": "351346869209",
        "pan": "FSJPR9338N",
        "dob": "",
        "gender": "Female",
        "native": "Pollachi"
    },
    "shibathaslin98@gmail.com": {
        "password": "Wps@12345",
        "name": "S.Shibathaslin",
        "employee_number": "WPS006",
        "phone": "6369765925",
        "parent_phone": "9345250972",
        "job_role": "Employee",
        "total_leave": 0,
        "total_working": 0,
        "address": "9A/1 anna nagar main road, vallam post. Thanjavur district. Tamilnadu. Pin - 613403.",
        "aadhaar": "669839855290",
        "pan": "KQWPS7422A",
        "dob": "",
        "gender": "Female",
        "native": "Pollachi"
    },
    "divyaariraman74@gmail.com": {
        "password": "Wps@12345",
        "name": "A Divya",
        "employee_number": "WPS007",
        "phone": "8973340133",
        "parent_phone": "9037387973",
        "job_role": "Employee",
        "total_leave": 0,
        "total_working": 0,
        "address": "Meenakshipuram",
        "aadhaar": "819276745462",
        "pan": "JKKPD5596K",
        "dob": "",
        "gender": "female",
        "native": "Pollachi"
    },
    "Hibamohamme04@gmail.com": {
        "password": "Wps@12345",
        "name": "Hiba. S",
        "employee_number": "WPS008",
        "phone": "7810044714",
        "parent_phone": "6382538436",
        "job_role": "Employee",
        "total_leave": 0,
        "total_working": 0,
        "address": "15/13-8 kls nagar, thozhilpettai, makkinampatti(po)",
        "aadhaar": "649957673013",
        "pan": "UCZPS0149K",
        "dob": "",
        "gender": "Female",
        "native": "Pollachi"
    },
    "fousichachu@gmail.com": {
        "password": "Wps@12345",
        "name": "FOUSIYA",
        "employee_number": "WPS009",
        "phone": "6382558401",
        "parent_phone": "9488203915",
        "job_role": "Employee",
        "total_leave": 0,
        "total_working": 0,
        "address": "NO.08 river street anaimalai",
        "aadhaar": "616195494253",
        "pan": "AGVPF2918H",
        "dob": "14.02.1998",
        "gender": "FEMALE",
        "native": ""
    },
    "dharanikrishnan2312@gmail.com": {
        "password": "Wps@12345",
        "name": "DHARANI",
        "employee_number": "WPS010",
        "phone": "9345769131",
        "parent_phone": "8883334092",
        "job_role": "Employee",
        "total_leave": 0,
        "total_working": 0,
        "address": "11/35 Pap colony vettaikaran pudhur anaimalai",
        "aadhaar": "885076433892",
        "pan": "GYEPDT283Q",
        "dob": "23.12.2001",
        "gender": "Female",
        "native": ""
    },
    "musthiriyab@gmail.com": {
        "password": "Wps@12345",
        "name": "MUSTHIRIYA BANU",
        "employee_number": "WPS011",
        "phone": "8056406069",
        "parent_phone": "8012072017",
        "job_role": "Employee",
        "total_leave": 0,
        "total_working": 0,
        "address": "91.4street INDIRA NAGAR ANAIMALAI",
        "aadhaar": "238281621636",
        "pan": "GRVPR9997H",
        "dob": "26.08.1998",
        "gender": "Female",
        "native": ""
    },
    "fowmilauhin1999@gmail.com": {
        "password": "Wps@12345",
        "name": "FOWMILA",
        "employee_number": "WPS012",
        "phone": "9688590658",
        "parent_phone": "9488251947",
        "job_role": "Employee",
        "total_leave": 0,
        "total_working": 0,
        "address": "1/22 INDIRA NAGAR ANAIMALAI",
        "aadhaar": "260413392484",
        "pan": "AFRPF8490H",
        "dob": "02.09.1999",
        "gender": "Female",
        "native": ""
    }
}
