users = {
    "sugunazugopvt@gmail.com": {
        "password": "zugo@123",
        "name": "SUGUNA SUNDARAJOTHI",
        "email": "sugunasundarajothi@gmail.com",
        "photo": "suguna.jpeg", 
        "joining_date": "21/08/2025",
        "employee_number": "ZPL001",
        "phone": "8344987196",
        "parent_phone": "9487504851",
        "dob": "18/06/2000",
        "gender": "Female",
        "job_role": "AI & ML DEVELOPER",
        "native": "The Nilgiris",
        "address": "19/3 Olimada , Uppatty post , Pandalur taluk ,The Nilgiris - 643241",
        "aadhar": "2756 1817 0839",
        "pan_card": "EFPSS3361R",
        "salary": "35,000",
        "bank_details": "State Bank of India, A/C No: 1234567890, IFSC: SBIN0001234",
        "total_leave": 0,  # Will be calculated/managed elsewhere
        "total_working": 0 # Will be calculated
    },
    "zugopvtnetwork@gmail.com": { # HR Account - Sindhu G
        "password": "zugo@123",
        "name": "SINDHU G",
        "email": "",
        "photo": "zugo logo.png", 
        "joining_date": "21/08/2025",
        "employee_number": "ZPLHR",
        "phone":"7305488701",
        "parent_phone": "9944922396",
        "dob": "03/05/2002",
        "gender": "Female",
        "job_role": "HR manager",
        "native": "Tiruppur",
        "address": "05, Thanner panthal colony Tiruppur 641 652",
        "aadhar": "6154 6184 1827",
        "pan_card": "",
        "bank_details": "",
        "salary": "",
        "total_leave": 0,
        "total_working": 0
    },
    "nandhakumarzugopvt@gmail.com": {
        "password": "nandha123",
        "name": "NANDHAKUMAR T",
        "email": "nandhakumar1152@gmail.com",
        "photo": "nandhu.jpg", 
        "joining_date": "30/08/2025",
        "employee_number": "ZPL010",
        "phone": "9360202144",
        "parent_phone": "7010110289",
        "dob": "15/03/2001",
        "gender": "Male",
        "job_role": "Video editor",
        "native": "Namakkal",
        "address": "3/324,murugankoil, salemroad,Namakkal - 637001",
        "aadhar": "2028 9976 5232",
        "pan_card": "",
        "bank_details": "",
        "salary": "",
        "total_leave": 0,
        "total_working": 0
    },
    "zugoprivitelimited.hr@gmail.com": {
        "password": "Sindhu@123",
        "name": "SINDHU G",
        "email": "sindhugnanasekaran609@gmail.com",
        "photo": "sindhu.jpeg", 
        "joining_date": "21/08/2025",
        "employee_number": "ZPL003",
        "phone":"7305488701",
        "parent_phone": "9944922396",
        "dob": "03/05/2002",
        "gender": "Female",
        "job_role": "HR manager",
        "native": "Tiruppur",
        "address": "05, Thanner panthal colony Tiruppur 641 652",
        "aadhar": "6154 6184 1827",
        "pan_card": "",
        "bank_details": "",
        "salary": "",
        "total_leave": 0,
        "total_working": 0
    },
     "nanthuzugopvt@gmail.com": {
        "password": "nanthu@123",
        "name": "NANTHAKUMAR K S",
        "email": "ksnandhakumarcgm@gmail.com",
        "photo": "Nanthu_ks.jpeg", 
        "joining_date": "21/08/2025",
        "employee_number": "ZPL002",
        "phone": "6379546463",
        "parent_phone": "8925685424",
        "dob": "24/10/2003",
        "gender": "Male",
        "job_role": "Web Developer",
        "native": "Thiruvannamalai",
        "address": "74, MGR Nagar, Rajaji Street, Chengam, Thiruvannamalai",
        "aadhar": "6162 1005 8657",
        "pan_card": "",
        "bank_details": "",
        "salary": "",
        "total_leave": 0,
        "total_working": 0
    },
    "arunzugopvt@gmail.com": {
        "password": "Arun@123",
        "name": "ARUN K",
        "email": "arunkumaradhik7@gmail.com",
        "photo": "arun.png", 
        "joining_date": "21/08/2025",
        "employee_number": "ZPL008",
        "phone": "7339100395",
        "parent_phone": "7550182906",
        "dob": "10/10/2001",
        "gender": "Male",
        "job_role": "Creative Designer",
        "native": "Chennai",
        "address": "6/9 kandhan kollai, Sevvappet, Thiruvallur ",
        "aadhar": "2248 2601 3305",
        "pan_card": "",
        "bank_details": "",
        "salary": "",
        "total_leave": 0,
        "total_working": 0
    },
     "bharathzugopvt@gmail.com": {
        "password": "bharath@123",
        "name": "BHARATH RAJ .M",
        "email": "bharath24112001@gmail.com",
        "photo": "bharath.JPG", 
        "joining_date": "21/08/2025",
        "employee_number": "ZPL005",
        "phone": "8667841036",
        "parent_phone": "9487560529",
        "dob": "24/11/2001",
        "gender": "male",
        "job_role": "Sales and marketing ",
        "native": "Tirupur",
        "address": "202/1b kuttivannan 1 at street samundipuram Tirupur 641603",
        "aadhar": "6072 9860 6570",
        "pan_card": "",
        "bank_details": "",
        "salary": "",
        "total_leave": 0,
        "total_working": 0
    },
    "someshzugopvt@gmail.com": {
        "password": "somesh@123",
        "name": "SOMESH KANNA",
        "email": "somsaf0411@gmail.com",
        "photo": "somesh.jpg", 
        "joining_date": "21/08/2015",
        "employee_number": "ZPL004",
        "phone": "9345784828",
        "parent_phone": "6374931974",
        "dob": "03/06/2005",
        "gender": "Male ",
        "job_role": "Social media manager",
        "native": "karaikudi",
        "address": "bharathi street,  kallal",
        "aadhar": "3655 3245 0652",
        "pan_card": "",
        "bank_details": "",
        "salary": "",
        "total_leave": 0,
        "total_working": 0
    },
    "sornakumarzugopvt@gmail.com": {
        "password": "Sorna@123",
        "name": "SORNAKUMAR",
        "email": "sornakumarzugopvt@gmail.com",
        "photo": "sornakumar.JPG", 
        "joining_date": "23/09/2025",
        "employee_number": "ZPL009",
        "phone": "8148789949",
        "parent_phone": "8190950457",
        "dob": "01/04/1984",
        "gender": "Male",
        "job_role": "Sales and marketing",
        "native": "Tirupur",
        "address": "246A , thiruneelakandar veethi 2 nd Street ,Thirumuruganpoondi,Tirupur_641652",
        "aadhar": "7874 0307 1611",
        "pan_card": "",
        "bank_details": "",
        "salary": "",
        "total_leave": 0,
        "total_working": 0
    },
    "pavithramzugopvt@gmail.com": {
        "password": "pavithra@123",
        "name": "M. PAVITHRA",
        "email": "pavithra.m2007@gmail.com",
        "photo": "static/pavithra.jpeg",
        "joining_date": "01/09/2025",
        "employee_number": "ZPL013",
        "phone": "7904928403",
        "parent_phone": "8765432109",
        "dob": "15/08/2000",
        "gender": "Female",
        "job_role": "Sales & Marketing",
        "native": "Tamil Nadu",
        "address": "Plot No. 45, Main Road, Coimbatore, Tamil Nadu - 641001",
        "aadhar": "9876 5432 1098",
        "pan_card": "HDQPP9823Q",
        "bank_details": "Tamilnad Mercantile Bank, A/C No: 075100050318845, IFSC: TMBL0000075",
        "salary": "",
        "total_leave": 0,
        "total_working": 0
    },
    "afrinzugopvt@gmail.com": {
        "password": "afrinA@123",
        "name": "A. AFRIN MEKHANAS",
        "email": "afrinappas56@gmail.com",
        "photo": "static/afrin.jpeg",
        "joining_date": "03/11/2025",
        "employee_number": "ZPL011",
        "phone": "9345164496",
        "parent_phone": "9965365768",
        "dob": "04/11/2004",
        "gender": "Female",
        "job_role": "Creative designer",
        "native": "Sivagangai",
        "address": "Sasiwarnapuram street, Okkur, Sivagangai",
        "aadhar": "4364 1864 3426",
        "pan_card": "",
        "bank_details": "Indian Bank, A/C No: 923497413, Branch: Okkur, IFSC: IDIB000O020",
        "salary": "",
        "total_leave": 0,
        "total_working": 0
    }
}